### ISSUE TITLE
Problems with Target 1.58

### ISSUE THREAD

**Issue by ISO8807** [buxtronix/target#2]
I have used Target for several years quite happily, but unfortunately the recent release is quite problematic. I did like the original layout...

The most serious problem is that the menu doesn't work (presuming this is what the ... button is for). This renders the game unusable. I am using a Samsung Galaxy Tab S with Android 6 (8.4" screen).

The Instructions are almost illegible. The font is small and contrasts poorly with the dark gray background.

Overall, the font sizes are a bit too small for comfort (e.g. the list of guessed words).

**Comment by buxtronix** [comment]
1.59b has been release recently. This should address the menu button problem. I'll get cracking at the instructions legibility problems next.

**Comment by ISO8807** [comment]
Many thanks for your prompt reply and action! Ken Turner
